name: Go CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ v8 ]
  pull_request:
    branches: [ v8 ]
    
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.20.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
          
    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -race
  
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
        
    - name: Run Coverage
      run: go test -coverprofile=coverage.txt -covermode=atomic
    
    - name: Upload Report
      run: bash <(curl -s https://codecov.io/bash)
